-- MySQL Script generated by MySQL Workbench
-- Sun May  8 21:07:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_ingCivil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_ingCivil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_ingCivil` DEFAULT CHARACTER SET utf8 ;
USE `db_ingCivil` ;

-- -----------------------------------------------------
-- Table `db_ingCivil`.`departamentos`
-- -----------------------------------------------------
create table departamentos(
id varchar(10) primary key,
nombre varchar(50) not null
);

-- -----------------------------------------------------
-- Table `db_ingCivil`.`municipios`
-- -----------------------------------------------------
create table municipios (
id_municipio varchar(10) primary key,
nombre_municipio varchar(100) not null,
id_departamento varchar(10),
FOREIGN KEY (id_departamento) REFERENCES departamentos(id)
);

-- -----------------------------------------------------
-- Table `db_ingCivil`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ingCivil`.`rol` (
  `id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db_ingCivil`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ingCivil`.`usuario` (
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(45) NOT NULL,
  `dirección` VARCHAR(45) NOT NULL,
  `nombre_unidad_edificación` VARCHAR(45) NOT NULL,
  `barrio` VARCHAR(45) NOT NULL,
  `nivel_formación` VARCHAR(45) NOT NULL,
  `departamentos_id_departamento` INT NOT NULL,
  `municipios_id_municipios` INT NOT NULL,
  `trataDatos` TINYINT NOT NULL,
  `rol_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cedula`),
  INDEX `fk_usuario_departamentos1_idx` (`departamentos_id_departamento` ASC) VISIBLE,
  INDEX `fk_usuario_municipios1_idx` (`municipios_id_municipios` ASC) VISIBLE,
  INDEX `fk_usuario_rol1_idx` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_departamentos1`
    FOREIGN KEY (`departamentos_id_departamento`)
    REFERENCES `db_ingCivil`.`departamentos` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_municipios1`
    FOREIGN KEY (`municipios_id_municipios`)
    REFERENCES `db_ingCivil`.`municipios` (`id_municipios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `db_ingCivil`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



-- -----------------------------------------------------
-- Table `db_ingCivil`.`tipoMaterial` YA---------------------
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ingCivil`.`tipoMaterial` (
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`descripcion`))



-- -----------------------------------------------------
-- Table `db_ingCivil`.`materialesContruccion` YA---------------------
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ingCivil`.`materialesContruccion` (
  `id` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `tipoMaterial_descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_materialesContruccion_tipoMaterial1_idx` (`tipoMaterial_descripcion` ASC) VISIBLE,
  CONSTRAINT `fk_materialesContruccion_tipoMaterial1`
    FOREIGN KEY (`tipoMaterial_descripcion`)
    REFERENCES `db_ingCivil`.`tipoMaterial` (`descripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



-- -----------------------------------------------------
-- Table `db_ingCivil`.`entrePisos` YA---------------------
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ingCivil`.`entrePisos` (
  `id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))



-- -----------------------------------------------------
-- Table `db_ingCivil`.`techos` YA---------------------------
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ingCivil`.`techos` (
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipo`))



-- -----------------------------------------------------
-- Table `db_ingCivil`.`asentamiento`  YA---------------------
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ingCivil`.`asentamiento` (
  `danoEdificacion` VARCHAR(45) NOT NULL,
  `ImgLejana` VARCHAR(45) NULL,
  `imgCercanaAObjeto` VARCHAR(45) NULL,
  PRIMARY KEY (`danoEdificacion`))



-- -----------------------------------------------------
-- Table `db_ingCivil`.`grietas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ingCivil`.`grietas` (
  `tieneGrietas` VARCHAR(45) NOT NULL,
  `ImgLejanaGrieta` VARCHAR(45) NULL,
  `ImgCercanaAObjeto` VARCHAR(45) NULL,
  PRIMARY KEY (`tieneGrietas`))


-- -----------------------------------------------------
-- Table `db_ingCivil`.`viviInt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ingCivil`.`viviInt` (
  `alturaEntrePisos` VARCHAR(45) NOT NULL,
  `materialConstruccion` VARCHAR(45) NOT NULL,
  `entrepiso` VARCHAR(45) NOT NULL,
  `edoEdificacion` VARCHAR(45) NOT NULL,
  `tieneGrietas` VARCHAR(45) NOT NULL,
  `materialesContruccion_id` INT NOT NULL,
  `entrePisos_id` INT NOT NULL,
  `tipoTechos_id` INT NOT NULL,
  `asentamiento_danoEdificacion` VARCHAR(45) NOT NULL,
  `grietas_tieneGrietas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`alturaEntrePisos`),
  INDEX `fk_viviInt_materialesContruccion1_idx` (`materialesContruccion_id` ASC) VISIBLE,
  INDEX `fk_viviInt_entrePisos1_idx` (`entrePisos_id` ASC) VISIBLE,
  INDEX `fk_viviInt_tipoTechos1_idx` (`tipoTechos_id` ASC) VISIBLE,
  INDEX `fk_viviInt_asentamiento1_idx` (`asentamiento_danoEdificacion` ASC) VISIBLE,
  INDEX `fk_viviInt_grietas1_idx` (`grietas_tieneGrietas` ASC) VISIBLE,
  CONSTRAINT `fk_viviInt_materialesContruccion1`
    FOREIGN KEY (`materialesContruccion_id`)
    REFERENCES `db_ingCivil`.`materialesContruccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viviInt_entrePisos1`
    FOREIGN KEY (`entrePisos_id`)
    REFERENCES `db_ingCivil`.`entrePisos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viviInt_tipoTechos1`
    FOREIGN KEY (`tipoTechos_id`)
    REFERENCES `db_ingCivil`.`techos` (`tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viviInt_asentamiento1`
    FOREIGN KEY (`asentamiento_danoEdificacion`)
    REFERENCES `db_ingCivil`.`asentamiento` (`danoEdificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viviInt_grietas1`
    FOREIGN KEY (`grietas_tieneGrietas`)
    REFERENCES `db_ingCivil`.`grietas` (`tieneGrietas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ingCivil`.`tipoEquipos`  YA_---------------------
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ingCivil`.`tipoEquipos` (
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipo`))


-- -----------------------------------------------------
-- Table `db_ingCivil`.`usos`   YA_---------------------------
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ingCivil`.`usos` (
  `id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))


-- -----------------------------------------------------
-- Table `db_ingCivil`.`viviExt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ingCivil`.`viviExt` (
  `area` FLOAT NOT NULL,
  `imgFrente` VARCHAR(200) NOT NULL,
  `ubicacionVivi` VARCHAR(45) NOT NULL,
  `cercaniasVivi` VARCHAR(45) NOT NULL,
  `usoActual` VARCHAR(45) NOT NULL,
  `usadoAnteriormente` VARCHAR(45) NOT NULL,
  `usoAnterior` VARCHAR(45) NOT NULL,
  `usoPrimPiso` VARCHAR(45) NOT NULL,
  `nPisos` INT NOT NULL,
  `ubicacicionPiso` INT NOT NULL,
  `nSotanos` INT NOT NULL,
  `equiposEnLaEdificacion` VARCHAR(45) NOT NULL,
  `comparte_piso` VARCHAR(45) NOT NULL,
  `tipoEquipos_tipo` VARCHAR(45) NOT NULL,
  `usos_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`area`),
  INDEX `fk_viviExt_tipoEquipos1_idx` (`tipoEquipos_tipo` ASC) VISIBLE,
  INDEX `fk_viviExt_usos1_idx` (`usos_id` ASC) VISIBLE,
  CONSTRAINT `fk_viviExt_tipoEquipos1`
    FOREIGN KEY (`tipoEquipos_tipo`)
    REFERENCES `db_ingCivil`.`tipoEquipos` (`tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viviExt_usos1`
    FOREIGN KEY (`usos_id`)
    REFERENCES `db_ingCivil`.`usos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ingCivil`.`viviGen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ingCivil`.`viviGen` (
  `año_construcción` VARCHAR(45) NOT NULL,
  `constructora` VARCHAR(45) NOT NULL,
  `nomConstructora` VARCHAR(45) NOT NULL,
  `usuario_cedula` VARCHAR(45) NOT NULL,
  `viviInt_alturaEntrePisos` INT NOT NULL,
  `viviExt_area` FLOAT NOT NULL,
  INDEX `fk_viviGen_usuario1_idx` (`usuario_cedula` ASC) VISIBLE,
  INDEX `fk_viviGen_viviInt1_idx` (`viviInt_alturaEntrePisos` ASC) VISIBLE,
  INDEX `fk_viviGen_viviExt1_idx` (`viviExt_area` ASC) VISIBLE,
  CONSTRAINT `fk_viviGen_usuario1`
    FOREIGN KEY (`usuario_cedula`)
    REFERENCES `db_ingCivil`.`usuario` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viviGen_viviInt1`
    FOREIGN KEY (`viviInt_alturaEntrePisos`)
    REFERENCES `db_ingCivil`.`viviInt` (`alturaEntrePisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viviGen_viviExt1`
    FOREIGN KEY (`viviExt_area`)
    REFERENCES `db_ingCivil`.`viviExt` (`area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
